apiVersion: v1
kind: Pod
metadata:
  name: pod-init-container
spec:
  initContainers:
    - name: test
      image: rkalluru/learnk8s:init-container-html-generator
      volumeMounts:
        - name: empty-dir
          mountPath: /mnt/html
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: empty-dir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: empty-dir
      emptyDir: {}

