apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
---
apiVersion: v1
kind: Pod
metadata:
  name: config-map-01
spec:
  containers:
    - name: test
      image: rkalluru/learnk8s:rhel9-bare
      env:
        - name: player_initial_lives
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: player_initial_lives
        - name: ui_properties_file_name
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: ui_properties_file_name


