apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app2
---
apiVersion: v1
kind: Secret
metadata:
  name: app1-sec
data:
  app1_sec1: dXNlci1pbnRlcmZhY2UucHJvcGVydGllcwo=
---
apiVersion: v1
kind: Secret
metadata:
  name: app2-sec
data:
  app1_sec1: dXNlci1pbnRlcmZhY2UucHJvcGVydGllcwo=
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: all-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: all-secrets
subjects:
- kind: ServiceAccount
  name: app1
  namespace: default
roleRef:
  kind: Role
  name: all-secrets
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: app1
spec:
  serviceAccountName: app1
  containers:
  - name: debug
    image: rkalluru/debug

