apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
    - name: pod
      image: nginx
      volumeMounts:
      - mountPath: "/opt"
        name: claim1
  volumes:
    - name: claim1
      persistentVolumeClaim:
        claimName: claim1
